In [1]:
import pandas as pd
import yfinance as yf

## Get the names of the S&P 500 constituent stocks from Wikipedia

In [2]:
sp500url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
data_table = pd.read_html(sp500url)

In [3]:
data_table

[    Symbol            Security             GICS Sector  \
 0      MMM                  3M             Industrials
 1      AOS         A. O. Smith             Industrials
 2      ABT              Abbott             Health Care
 3     ABBV              AbbVie             Health Care
 4      ACN           Accenture  Information Technology
 ..     ...                 ...                     ...
 498    XYL          Xylem Inc.             Industrials
 499    YUM         Yum! Brands  Consumer Discretionary
 500   ZBRA  Zebra Technologies  Information Technology
 501    ZBH       Zimmer Biomet             Health Care
 502    ZTS              Zoetis             Health Care

                                 GICS Sub-Industry    Headquarters Location  \
 0                        Industrial Conglomerates    Saint Paul, Minnesota
 1                               Building Products     Milwaukee, Wisconsin
 2                           Health Care Equipment  North Chicago, Illinois
 3                                   Biotechnology  North Chicago, Illinois
 4                  IT Consulting & Other Services          Dublin, Ireland
 ..                                            ...                      ...
 498  Industrial Machinery & Supplies & Components   White Plains, New York
 499                                   Restaurants     Louisville, Kentucky
 500            Electronic Equipment & Instruments   Lincolnshire, Illinois
 501                         Health Care Equipment          Warsaw, Indiana
 502                               Pharmaceuticals   Parsippany, New Jersey

      Date added      CIK      Founded
 0    1957-03-04    66740         1902
 1    2017-07-26    91142         1916
 2    1957-03-04     1800         1888
 3    2012-12-31  1551152  2013 (1888)
 4    2011-07-06  1467373         1989
 ..          ...      ...          ...
 498  2011-11-01  1524472         2011
 499  1997-10-06  1041061         1997
 500  2019-12-23   877212         1969
 501  2001-08-07  1136869         1927
 502  2013-06-21  1555280         1952

 [503 rows x 8 columns],
                   Date  Added                                Removed  \
                   Date Ticker                       Security  Ticker
 0          May 8, 2024    VST                         Vistra     PXD
 1        April 3, 2024    NaN                            NaN    XRAY
 2        April 3, 2024    NaN                            NaN     VFC
 3        April 2, 2024    GEV                     GE Vernova     NaN
 4        April 1, 2024   SOLV                      Solventum     NaN
 ..                 ...    ...                            ...     ...
 340       June 9, 1999    WLP                      Wellpoint     HPH
 341  December 11, 1998    FSR                        Firstar     LDW
 342  December 11, 1998    CCL                 Carnival Corp.     GRN
 343  December 11, 1998   CPWR                      Compuware     SUN
 344      June 17, 1997    CCI  Countrywide Credit Industries     USL

                                 \
                       Security
 0    Pioneer Natural Resources
 1              Dentsply Sirona
 2               VF Corporation
 3                          NaN
 4                          NaN
 ..                         ...
 340   Harnischfeger Industries
 341                      Amoco
 342                 General Re
 343                 SunAmerica
 344                     USLife

                                                 Reason
                                                 Reason
 0    S&P 500 and S&P 100 constituent ExxonMobil acq...
 1                     Market capitalization change.[5]
 2                     Market capitalization change.[5]
 3    S&P 500 and 100 constituent General Electric C...
 4    S&P 500 and 100 constituent 3M Co. spun off So...
 ..                                                 ...
 340           Harnischfeger filed for bankruptcy.[255]
 341                           BP purchased Amoco.[256]
 342      Berkshire Hathaway purchased General Re.[256]
 343                     AIG purchased SunAmerica.[256]
 344                          AIG acquired USLife.[257]

 [345 rows x 6 columns]]

In [4]:
len(data_table)

2

In [5]:
data_table[0]

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [6]:
data_table[0]['Symbol']

0       MMM
1       AOS
2       ABT
3      ABBV
4       ACN
       ...
498     XYL
499     YUM
500    ZBRA
501     ZBH
502     ZTS
Name: Symbol, Length: 503, dtype: object

In [7]:
data_table[0]['Symbol'].tolist()

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BK',
 'BBWI',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BLDR',
 'BG',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CTLT',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CHRW',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DAY',
 'DECK',
 'DE',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'LLY',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'ETSY',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TFX',
 'TER',
 'TSLA',
 'TXN',
 'TXT',
 'TMO',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WRK',
 'WY',
 'WMB',
 'WTW',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [8]:
tickers = data_table[0]['Symbol'].tolist()
tickers

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BK',
 'BBWI',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BLDR',
 'BG',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CTLT',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CHRW',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DAY',
 'DECK',
 'DE',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'LLY',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'ETSY',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TFX',
 'TER',
 'TSLA',
 'TXN',
 'TXT',
 'TMO',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WRK',
 'WY',
 'WMB',
 'WTW',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [9]:
len(tickers)

503

## Then import the stock prices through Yahoo Finance based on the list of stock names

In [10]:
snp_prices = yf.download(tickers)

[**********************45%%                      ]  228 of 503 completed

$BF.B: possibly delisted; No price data found  (1d 1925-07-12 -> 2024-06-17)

[*********************100%%**********************]  503 of 503 completed

2 Failed downloads:
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; No price data found  (1d 1925-07-12 -> 2024-06-17)')
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')

In [11]:
snp_prices

Price        Adj Close                                                         \
Ticker               A    AAL        AAPL        ABBV        ABNB         ABT
Date
1962-01-02         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-03         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-04         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-05         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-08         NaN    NaN         NaN         NaN         NaN         NaN
...                ...    ...         ...         ...         ...         ...
2024-06-11  132.110001  11.28  207.149994  167.699997  147.750000  105.809998
2024-06-12  133.160004  11.50  213.070007  166.089996  149.320007  104.379997
2024-06-13  130.570007  11.44  214.240005  166.559998  146.100006  103.449997
2024-06-14  129.850006  11.28  212.490005  168.589996  145.970001  103.680000
2024-06-17  131.830002  11.44  216.669998  169.679993  149.500000  103.449997

Price                                                      ...    Volume  \
Ticker           ACGL         ACN        ADBE         ADI  ...       WTW
Date                                                       ...
1962-01-02        NaN         NaN         NaN         NaN  ...       NaN
1962-01-03        NaN         NaN         NaN         NaN  ...       NaN
1962-01-04        NaN         NaN         NaN         NaN  ...       NaN
1962-01-05        NaN         NaN         NaN         NaN  ...       NaN
1962-01-08        NaN         NaN         NaN         NaN  ...       NaN
...               ...         ...         ...         ...  ...       ...
2024-06-11  99.580002  294.220001  462.690002  236.300003  ...  493600.0
2024-06-12  99.160004  285.730011  459.869995  238.440002  ...  440900.0
2024-06-13  99.150002  282.320007  458.739990  234.029999  ...  263300.0
2024-06-14  97.260002  286.709991  525.309998  231.190002  ...  324800.0
2024-06-17  99.209999  285.529999  518.739990  232.389999  ...  489500.0

Price                                                                        \
Ticker             WY       WYNN        XEL       XOM        XYL        YUM
Date
1962-01-02        NaN        NaN        NaN    902400        NaN        NaN
1962-01-03        NaN        NaN        NaN   1200000        NaN        NaN
1962-01-04        NaN        NaN        NaN   1088000        NaN        NaN
1962-01-05        NaN        NaN        NaN   1222400        NaN        NaN
1962-01-08        NaN        NaN        NaN   1388800        NaN        NaN
...               ...        ...        ...       ...        ...        ...
2024-06-11  3152800.0  2077500.0  3273600.0  12462400   725400.0  2149700.0
2024-06-12  3590800.0  2048700.0  3006100.0  13606800   669600.0  1279900.0
2024-06-13  3726400.0  1627100.0  3339800.0  14466900   818900.0  1554700.0
2024-06-14  3378000.0  2688600.0  2400600.0  13313400   883100.0  1418500.0
2024-06-17  3382500.0  1832700.0  2255900.0  21138500  1173900.0  1327800.0

Price
Ticker            ZBH      ZBRA        ZTS
Date
1962-01-02        NaN       NaN        NaN
1962-01-03        NaN       NaN        NaN
1962-01-04        NaN       NaN        NaN
1962-01-05        NaN       NaN        NaN
1962-01-08        NaN       NaN        NaN
...               ...       ...        ...
2024-06-11  3036000.0  172900.0  1844100.0
2024-06-12  2996500.0  191600.0  2068300.0
2024-06-13  1471000.0  303000.0  2298800.0
2024-06-14  1611400.0  218800.0  2225300.0
2024-06-17  1579200.0  306400.0  1650500.0

[15722 rows x 3018 columns]

In [12]:
snp_prices.isna().any()

Price      Ticker
Adj Close  A         True
           AAL       True
           AAPL      True
           ABBV      True
           ABNB      True
                     ...
Volume     XYL       True
           YUM       True
           ZBH       True
           ZBRA      True
           ZTS       True
Length: 3018, dtype: bool

In [13]:
snp_prices.loc[:, snp_prices.isna().any()]

Price        Adj Close                                                         \
Ticker               A    AAL        AAPL        ABBV        ABNB         ABT
Date
1962-01-02         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-03         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-04         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-05         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-08         NaN    NaN         NaN         NaN         NaN         NaN
...                ...    ...         ...         ...         ...         ...
2024-06-11  132.110001  11.28  207.149994  167.699997  147.750000  105.809998
2024-06-12  133.160004  11.50  213.070007  166.089996  149.320007  104.379997
2024-06-13  130.570007  11.44  214.240005  166.559998  146.100006  103.449997
2024-06-14  129.850006  11.28  212.490005  168.589996  145.970001  103.680000
2024-06-17  131.830002  11.44  216.669998  169.679993  149.500000  103.449997

Price                                                      ...    Volume  \
Ticker           ACGL         ACN        ADBE         ADI  ...       WST
Date                                                       ...
1962-01-02        NaN         NaN         NaN         NaN  ...       NaN
1962-01-03        NaN         NaN         NaN         NaN  ...       NaN
1962-01-04        NaN         NaN         NaN         NaN  ...       NaN
1962-01-05        NaN         NaN         NaN         NaN  ...       NaN
1962-01-08        NaN         NaN         NaN         NaN  ...       NaN
...               ...         ...         ...         ...  ...       ...
2024-06-11  99.580002  294.220001  462.690002  236.300003  ...  625900.0
2024-06-12  99.160004  285.730011  459.869995  238.440002  ...  810100.0
2024-06-13  99.150002  282.320007  458.739990  234.029999  ...  687800.0
2024-06-14  97.260002  286.709991  525.309998  231.190002  ...  374600.0
2024-06-17  99.209999  285.529999  518.739990  232.389999  ...  514700.0

Price                                                                        \
Ticker           WTW         WY       WYNN        XEL        XYL        YUM
Date
1962-01-02       NaN        NaN        NaN        NaN        NaN        NaN
1962-01-03       NaN        NaN        NaN        NaN        NaN        NaN
1962-01-04       NaN        NaN        NaN        NaN        NaN        NaN
1962-01-05       NaN        NaN        NaN        NaN        NaN        NaN
1962-01-08       NaN        NaN        NaN        NaN        NaN        NaN
...              ...        ...        ...        ...        ...        ...
2024-06-11  493600.0  3152800.0  2077500.0  3273600.0   725400.0  2149700.0
2024-06-12  440900.0  3590800.0  2048700.0  3006100.0   669600.0  1279900.0
2024-06-13  263300.0  3726400.0  1627100.0  3339800.0   818900.0  1554700.0
2024-06-14  324800.0  3378000.0  2688600.0  2400600.0   883100.0  1418500.0
2024-06-17  489500.0  3382500.0  1832700.0  2255900.0  1173900.0  1327800.0

Price
Ticker            ZBH      ZBRA        ZTS
Date
1962-01-02        NaN       NaN        NaN
1962-01-03        NaN       NaN        NaN
1962-01-04        NaN       NaN        NaN
1962-01-05        NaN       NaN        NaN
1962-01-08        NaN       NaN        NaN
...               ...       ...        ...
2024-06-11  3036000.0  172900.0  1844100.0
2024-06-12  2996500.0  191600.0  2068300.0
2024-06-13  1471000.0  303000.0  2298800.0
2024-06-14  1611400.0  218800.0  2225300.0
2024-06-17  1579200.0  306400.0  1650500.0

[15722 rows x 2874 columns]

#### After check Weki, we find that BRK.B is Berkshire Hathaway Inc. and BF.B is Brown-Forman Corporation, they use - instead of . in their tickers

In [14]:
yf.download('BF-B')['Adj Close']

[*********************100%%**********************]  1 of 1 completed

Date
1980-03-17     0.194453
1980-03-18     0.194453
1980-03-19     0.197055
1980-03-20     0.197705
1980-03-21     0.195104
                ...
2024-06-11    43.180000
2024-06-12    42.910000
2024-06-13    42.830002
2024-06-14    43.660000
2024-06-17    44.189999
Name: Adj Close, Length: 11157, dtype: float64

In [15]:
yf.download('BRk-B')['Adj Close']

[*********************100%%**********************]  1 of 1 completed

Date
1996-05-09     23.200001
1996-05-10     24.000000
1996-05-13     23.900000
1996-05-14     23.600000
1996-05-15     23.200001
                 ...
2024-06-11    408.500000
2024-06-12    408.769989
2024-06-13    405.920013
2024-06-14    405.540009
2024-06-17    407.320007
Name: Adj Close, Length: 7074, dtype: float64

In [16]:
for i in range(len(tickers)):
    if tickers[i] == 'BF.B':
        tickers[i] = 'BF-B'
    elif tickers[i] == 'BRK.B':
        tickers[i] = 'BRK-B'

In [17]:
'BF-B' in tickers
'BRK-B' in tickers

True

## Change the code to whatever period you want

In [18]:
snp_prices = yf.download(tickers, start='2014-06-15', end='2024-06-15')['Adj Close']

[*********************100%%**********************]  503 of 503 completed

In [21]:
snp_prices.to_csv('snp_prices.csv')

## Transpose the data to make it easier to use in the future

In [20]:
snp_prices_transpose = snp_prices.T
snp_prices_transpose.head()

Date,2014-06-16,2014-06-17,2014-06-18,2014-06-19,2014-06-20,2014-06-23,2014-06-24,2014-06-25,2014-06-26,2014-06-27,...,2024-06-03,2024-06-04,2024-06-05,2024-06-06,2024-06-07,2024-06-10,2024-06-11,2024-06-12,2024-06-13,2024-06-14
Ticker,,,,,,,,,,,,,,,,,,,,,
A,38.350636,38.712307,38.975330,38.547913,38.646545,38.212532,37.910042,38.120468,38.021828,37.897919,...,131.399994,130.850006,133.559998,132.820007,132.979996,133.029999,132.110001,133.160004,130.570007,129.850006
AAL,38.708969,39.472584,40.217354,40.594448,41.999138,41.820011,40.707577,41.395779,41.999138,41.480625,...,11.530000,11.500000,11.620000,11.430000,11.500000,11.490000,11.280000,11.500000,11.440000,11.280000
AAPL,20.416189,20.389618,20.411760,20.340904,20.130541,20.112825,19.991043,20.008753,20.128330,20.367474,...,194.029999,194.350006,195.869995,194.479996,196.889999,193.119995,207.149994,213.070007,214.240005,212.490005
ABBV,35.777485,35.976238,36.155144,35.903358,35.313709,35.611847,35.505844,36.440037,37.440472,37.625996,...,160.190002,162.139999,165.440002,168.570007,169.419998,170.460007,167.699997,166.089996,166.559998,168.589996
ABNB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,146.250000,147.080002,145.779999,147.000000,146.660004,148.070007,147.750000,149.320007,146.100006,145.970001